include makefile_common.mk

.DEFAULT_GOAL := all


# Choose permissible app area IDs
ifeq ($(bl_updater_match_app_area_id),no)
# Match any app area ID
MATCH_APP_AREA_ID :=
else
ifeq ($(bl_updater_match_app_area_id),yes)
# Match only the app area ID of the application being built
MATCH_APP_AREA_ID := $(app_area_id)
else
# Match multiple app area IDs, including the application being built
MATCH_APP_AREA_ID := $(app_area_id),$(bl_updater_match_app_area_id)
endif
endif

# Reset areas to those in the new INI file, or keep areas
ifeq ($(bl_updater_reset_areas),yes)
RESET_AREAS := "--reset_areas"
else
RESET_AREAS :=
endif

# Include HAL driver code, needed to link bootloader updater
#
# This populates SRCS and ASM_SRCS
-include $(HAL_API_PATH)makefile

#INCLUDES += -iquote$(API_PATH) -I$(UTIL_PATH)

stack_mode ?= normal
modemfw_name ?=

# The bootloader library, which includes the Generic Bootloader Updater Tool
BOOTLOADER_LIB := $(BUILDPREFIX_BOOTLOADER)bootloader.a

# Entry point for the bootloader updater and the second stage loader
ENTRYPOINT_ASM := $(MCU_PATH)common/bl_updater_entrypoint.s

# Compiled entry point for the bootloader updater
ENTRYPOINT_OBJ = $(BUILDPREFIX_BL_UPDATER)bl_updater_entrypoint.o

# Compiled entry point for the second stage loader
ENTRYPOINT_2ND_OBJ = $(BUILDPREFIX_BL_UPDATER)bl_updater_entrypoint_2nd.o

# Compiled and linked bootloader updater
BL_UPDATER_ELF := $(BL_UPDATER_HEX:.hex=.elf)

# Compiled and linked second stage loader
BL_UPDATER_2ND_HEX := $(BUILDPREFIX_BL_UPDATER)bl_updater_2nd.hex
BL_UPDATER_2ND_ELF := $(BL_UPDATER_2ND_HEX:.hex=.elf)

# Command list for bootloader updater
COMMAND_LIST := $(APP_SRCS_PATH)COMMAND_LIST.conf

# Scratchpads with stack for new and old bootloaders
SCRATCHPAD_FOR_OLD_BL := $(BUILDPREFIX_BL_UPDATER)wpc_stack_for_old_bl.otap
SCRATCHPAD_FOR_NEW_BL := $(BUILDPREFIX_BL_UPDATER)wpc_stack_for_new_bl.otap

# Bootloader configuration data, generated by bl_updater_config.py
GEN_CONFIG_SRCS_ := bl_updater_config_blupd2.c
GEN_CONFIG_SRCS_ += encrypt_key_for_old_bl.c encrypt_key_for_new_bl.c
GEN_CONFIG_SRCS := $(addprefix $(BUILDPREFIX_BL_UPDATER), $(GEN_CONFIG_SRCS_))

# Other files generated by bl_updater_config.py
GEN_SRCS_ := new_bootloader_data.c
GEN_SRCS_ += scratchpad_prefix_for_old_bl.c scratchpad_prefix_for_new_bl.c
GEN_SRCS_ += ctr_advance_for_old_bl.c ctr_advance_for_new_bl.c
GEN_SRCS_ += scratchpad_file_headers.c scratchpad_file_data.c
GEN_SRCS := $(addprefix $(BUILDPREFIX_BL_UPDATER), $(GEN_SRCS_))

# This makefile, needed for re-reading it after generating a makefile fragment
THIS_MAKEFILE := $(firstword $(MAKEFILE_LIST))

# Source files for bootloader updater
SRCS_BL_UPDATER := $(SRCS) $(notdir $(GEN_CONFIG_SRCS) $(GEN_SRCS))
ASM_SRCS_BL_UPDATER := $(ASM_SRCS)

# Objects files for bootloader updater
OBJS_BL_UPDATER_ := $(SRCS_BL_UPDATER:.c=.o) $(ASM_SRCS_BL_UPDATER:.s=.o)
OBJS_BL_UPDATER := $(addprefix $(BUILDPREFIX_BL_UPDATER), $(OBJS_BL_UPDATER_))

# Object files for second stage loader
OBJS_2ND_STAGE_ := $(SRCS:.c=.o) $(ASM_SRCS:.s=.o)
OBJS_2ND_STAGE_ += bl_updater_config_blupd2.o encrypt_key_for_old_bl.o
OBJS_2ND_STAGE := $(addprefix $(BUILDPREFIX_BL_UPDATER), $(OBJS_2ND_STAGE_))

# Do not print a warning when linking code to RAM ("bl_updater.elf
# has a LOAD segment with RWX permissions")
LDFLAGS += -Wl,--no-warn-rwx-segments

# Linker script for the bootloader updater and the second stage loader
ifndef MCU_RAM_VAR
LDSCRIPT_BL_UPDATER = $(MCU_PATH)$(MCU_FAMILY)/$(MCU)/linker/gcc_bl_updater_$(MCU)$(MCU_SUB)$(MCU_MEM_VAR).ld
else
LDSCRIPT_BL_UPDATER = $(MCU_PATH)$(MCU_FAMILY)/$(MCU)/linker/gcc_bl_updater_$(MCU)$(MCU_SUB)$(MCU_MEM_VAR)_$(MCU_RAM_VAR).ld
endif

# Files to be cleaned
CLEAN := $(OBJS_BL_UPDATER) $(OBJS_2ND_STAGE) $(GEN_CONFIG_SRCS) $(GEN_SRCS)
CLEAN += $(BL_UPDATER_HEX) $(BL_UPDATER_ELF) $(ENTRYPOINT_OBJ)
CLEAN += $(BL_UPDATER_2ND_HEX) $(BL_UPDATER_2ND_ELF)  $(ENTRYPOINT_2ND_OBJ)
CLEAN += $(BL_UPDATER_OLD_CONFIG_INI) $(BL_UPDATER_BUILD_VARIABLES_MK)
CLEAN += $(SCRATCHPAD_FOR_OLD_BL) $(SCRATCHPAD_FOR_NEW_BL)


# Functions

define GENERATE_CONFIG_INI
	@echo "$(COLOR_INFO)Generating:$(COLOR_END) $(BL_UPDATER_BUILD_VARIABLES_MK)"

	@# Generate config file for the old bootloader
	$(DD)$(MKDIR) $(@D)
	$(D)$(BOOT_CONF) \
	    -i $(ini_file_wp) \
	    -i $(ini_file_app) \
	    -i $(platform_config_ini) \
	    -i $(bl_updater_old_key_file) \
	    -o $(BL_UPDATER_OLD_CONFIG_INI) \
	    -om $(BL_UPDATER_BUILD_VARIABLES_MK) \
	    -vp "old_bl_" \
	    -ol APP_AREA_ID:$(app_area_id) \
	    -hm 0x$(HW_MAGIC) \
	    -hv 0x$(HW_VARIANT_ID) \
	    -fb $(FLASH_BASE_ADDR) \
	    -bs $(old_bootloader_size) \
	    -as $(BOOTLOADER_SIZES)
endef

define GENERATE_STACK_SCRATCHPADS
	@echo "$(COLOR_INFO)Generating:$(COLOR_END) stack scratchpads"

	$(DD)$(MKDIR) $(@D)

	@# Only add second stage loader to the scratchpad if area IDs differ
	$(DD)if test $(old_bl_stack_area_id) = $(stack_area_id); then \
	    export SECOND_STAGE_DEF=; \
	else \
	    export \
	        SECOND_STAGE_DEF=$(STACK_CONF):$(old_bl_stack_area_id):$(BL_UPDATER_2ND_HEX); \
	fi; \
	 \
	$(SCRAT_GEN) \
	    --configfile=$(BL_UPDATER_OLD_CONFIG_INI) \
	    $(SCRATCHPAD_FOR_OLD_BL) \
	    $$SECOND_STAGE_DEF \
	    $(STACK_CONF):$(stack_area_id):$(STACK_HEX); \
	 \
	$(SCRAT_GEN) \
	    --configfile=$(BOOTLOADER_CONFIG_INI) \
	    $(SCRATCHPAD_FOR_NEW_BL) \
	    $$SECOND_STAGE_DEF \
	    $(STACK_CONF):$(stack_area_id):$(STACK_HEX)
endef

define GENERATE_CONFIG_DATA
	$(DD)$(MKDIR) $(@D)
	@echo "$(COLOR_INFO)Converting:$(COLOR_END) new bootloader configuration"
	$(D)$(BL_UPD_CONF) \
	    config_to_data \
	    $(BUILDPREFIX_BL_UPDATER) \
	    $(COMMAND_LIST) \
	    --config_file=$(BOOTLOADER_CONFIG_INI) \
	    --old_config_file=$(BL_UPDATER_OLD_CONFIG_INI) \
	    --match_app_area_id=$(MATCH_APP_AREA_ID) \
	    $(RESET_AREAS)

	$(DD)$(MKDIR) $(@D)
	@echo "$(COLOR_INFO)Converting:$(COLOR_END) scratchpad keys"
	$(D)$(BL_UPD_CONF) \
	    keys_to_data \
	    $(BUILDPREFIX_BL_UPDATER) \
	    --old_config_file=$(BL_UPDATER_OLD_CONFIG_INI) \
	    --config_file=$(BOOTLOADER_CONFIG_INI)
endef

define GENERATE_BL_SCRATCHPAD_DATA
	$(DD)$(MKDIR) $(@D)

	@echo "$(COLOR_INFO)Converting:$(COLOR_END) new bootloader"
	$(D)$(BL_UPD_CONF) \
	    bl_to_data \
	    $(BUILDPREFIX_BL_UPDATER) \
	    $(BOOTLOADER_HEX) \
	    --config_file=$(BOOTLOADER_CONFIG_INI)

	$(DD)$(MKDIR) $(@D)
	@echo "$(COLOR_INFO)Converting:$(COLOR_END) stack scratchpads"
	$(D)$(BL_UPD_CONF) \
	    scratchpads_to_data \
	    $(BUILDPREFIX_BL_UPDATER) \
	    $(SCRATCHPAD_FOR_OLD_BL) $(SCRATCHPAD_FOR_NEW_BL) \
	    --old_config_file=$(BL_UPDATER_OLD_CONFIG_INI) \
	    --config_file=$(BOOTLOADER_CONFIG_INI)
endef


# Target rules

# Generate a scratchpads for embedding in the bootloader updater
$(SCRATCHPAD_FOR_NEW_BL) $(SCRATCHPAD_FOR_OLD_BL): $(BOOTLOADER_CONFIG_INI) $(BL_UPDATER_OLD_CONFIG_INI) $(BL_UPDATER_2ND_HEX) $(STACK_HEX)
	$(call GENERATE_STACK_SCRATCHPADS)

# Link entrypoint, bootloader updater library, embedded stack-only
# scratchpad, new bootloader, and bootloader updater config
$(BL_UPDATER_ELF): $(ENTRYPOINT_OBJ) $(OBJS_BL_UPDATER) $(BOOTLOADER_LIB)
	$(DD)$(MKDIR) $(@D)
	@echo "$(COLOR_LINK)Linking$(COLOR_END) $@"
	$(D)$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $^ \
	          -Wl,--defsym,__bootloader_area_addr__=$(old_bl_bootloader_area_addr) \
	          -Wl,--defsym,__bootloader_area_length__=$(old_bl_bootloader_area_length) \
	          -Wl,--defsym,__stack_area_addr__=$(old_bl_stack_area_addr) \
	          -Wl,--defsym,__stack_area_length__=$(old_bl_stack_area_length) \
	          -Wl,--defsym,__keepout_length__=16384 \
	          -Wl,-Map=$(BUILDPREFIX_BL_UPDATER)bl_updater.map \
	          -Wl,-T,$(LDSCRIPT_BL_UPDATER) \
	          $(LIBS)

# Link second stage loader with entrypoint and bootloader updater library
$(BL_UPDATER_2ND_ELF): $(ENTRYPOINT_2ND_OBJ) $(OBJS_2ND_STAGE) $(BOOTLOADER_LIB)
	$(DD)$(MKDIR) $(@D)
	@echo "$(COLOR_LINK)Linking$(COLOR_END) $@"
	$(D)$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $^ \
	          -Wl,--defsym,__bootloader_area_addr__=$(old_bl_bootloader_area_addr) \
	          -Wl,--defsym,__bootloader_area_length__=$(old_bl_bootloader_area_length) \
	          -Wl,--defsym,__stack_area_addr__=$(old_bl_stack_area_addr) \
	          -Wl,--defsym,__stack_area_length__=$(old_bl_stack_area_length) \
	          -Wl,--defsym,__keepout_length__=0 \
	          -Wl,-Map=$(BUILDPREFIX_BL_UPDATER)bl_updater_2nd.map \
	          -Wl,-T,$(LDSCRIPT_BL_UPDATER) \
	          $(LIBS)

$(BUILDPREFIX_BL_UPDATER)%.hex: $(BUILDPREFIX_BL_UPDATER)%.elf
	$(DD)$(MKDIR) $(@D)
	@echo "$(COLOR_INFO)Generating:$(COLOR_END) $@"
	$(D)$(OBJCOPY) $< -O ihex $@

$(GEN_CONFIG_SRCS): $(BL_UPDATER_OLD_CONFIG_INI) $(BOOTLOADER_CONFIG_INI)
	$(call GENERATE_CONFIG_DATA)

$(GEN_SRCS): $(BOOTLOADER_HEX) $(SCRATCHPAD_FOR_OLD_BL) $(SCRATCHPAD_FOR_NEW_BL) $(BL_UPDATER_OLD_CONFIG_INI) $(BOOTLOADER_CONFIG_INI)
	$(call GENERATE_BL_SCRATCHPAD_DATA)

$(BUILDPREFIX_BL_UPDATER)%.o: %.c
	$(DD)$(MKDIR) $(@D)
	@echo "$(COLOR_CC)CC$(COLOR_END) $<"
	$(D)$(CC) $(INCLUDES) $(CFLAGS) -MMD -MP -c $< -o $@

$(BUILDPREFIX_BL_UPDATER)%.o: $(BUILDPREFIX_BL_UPDATER)%.c
	$(DD)$(MKDIR) $(@D)
	@echo "$(COLOR_CC)CC$(COLOR_END) $<"
	$(D)$(CC) $(INCLUDES) $(CFLAGS) -MMD -MP -c $< -o $@

$(BUILDPREFIX_BL_UPDATER)%.o: %.s
	$(DD)$(MKDIR) $(@D)
	@echo "$(COLOR_CC)CC$(COLOR_END) $<"
	$(D)$(CC) $(INCLUDES) $(CFLAGS) -c $< -o $@

$(ENTRYPOINT_OBJ): $(ENTRYPOINT_ASM)
	$(DD)$(MKDIR) $(@D)
	@echo "$(COLOR_CC)CC$(COLOR_END) $<"
	$(D)$(CC) $(INCLUDES) $(CFLAGS) \
	          -Wa,-defsym,BOOTLOADER_UPDATER=1 \
	          -Wa,-defsym,SECOND_STAGE_LOADER=0 \
	          -c $< -o $@

$(ENTRYPOINT_2ND_OBJ): $(ENTRYPOINT_ASM)
	$(DD)$(MKDIR) $(@D)
	@echo "$(COLOR_CC)CC$(COLOR_END) $<"
	$(D)$(CC) $(INCLUDES) $(CFLAGS) \
	          -Wa,-defsym,BOOTLOADER_UPDATER=0 \
	          -Wa,-defsym,SECOND_STAGE_LOADER=1 \
	          -c $< -o $@

# Prevent initial makefile fragment generation happening in the wrong order
.NOTPARALLEL: $(BL_UPDATER_BUILD_VARIABLES_MK) $(THIS_MAKEFILE)

# Ensure that this makefile is re-read when
# the makefile fragment is generated below
$(THIS_MAKEFILE): $(BL_UPDATER_BUILD_VARIABLES_MK)

# Generate full bootloader configuration and a makefile fragment that match the
# old bootloader configuration as well as the embedded stack configuration
$(BL_UPDATER_OLD_CONFIG_INI) $(BL_UPDATER_BUILD_VARIABLES_MK): $(ini_file_wp) $(ini_file_app) $(bl_updater_old_key_file)
	$(call GENERATE_CONFIG_INI)

# Include a makefile fragment for build-time
# make variables, generated by the rule above
-include $(BL_UPDATER_BUILD_VARIABLES_MK)

.PHONY: all
all: $(BL_UPDATER_HEX)

clean:
	$(D)$(RM) -rf $(CLEAN)
