var examples =
[
    [ "aes/app.c", "de/dde/aes_2app_8c-example.html", null ],
    [ "app_persistent/app.c", "dc/d74/app_persistent_2app_8c-example.html", null ],
    [ "appconfig/app.c", "d0/dd1/appconfig_2app_8c-example.html", null ],
    [ "basic_interrupt/app.c", "d1/dac/basic_interrupt_2app_8c-example.html", null ],
    [ "battery_voltage_read_app/app.c", "db/df3/battery_voltage_read_app_2app_8c-example.html", null ],
    [ "ble_scanner/app.c", "d7/d1c/ble_scanner_2app_8c-example.html", null ],
    [ "ble_tx/app.c", "d3/d63/ble_tx_2app_8c-example.html", null ],
    [ "blink/app.c", "d3/d9c/blink_2app_8c-example.html", null ],
    [ "board/efr32_template/bootloader/early_init_efr32.c", "d1/de1/board_2efr32_template_2bootloader_2early_init_efr32_8c-example.html", null ],
    [ "control_node/app.c", "d2/d53/control_node_2app_8c-example.html", null ],
    [ "control_router/app.c", "d4/ddd/control_router_2app_8c-example.html", null ],
    [ "custom_app/app.c", "db/d83/custom_app_2app_8c-example.html", null ],
    [ "debug/app.c", "dd/d80/debug_2app_8c-example.html", null ],
    [ "diradv/app.c", "d7/d41/diradv_2app_8c-example.html", null ],
    [ "dualmcu_app/app.c", "da/d1e/dualmcu_app_2app_8c-example.html", null ],
    [ "evaluation_app/app.c", "df/dc0/evaluation_app_2app_8c-example.html", null ],
    [ "inventory_app_router/app.c", "df/d91/inventory_app_router_2app_8c-example.html", null ],
    [ "inventory_app_tag/app.c", "d3/d2f/inventory_app_tag_2app_8c-example.html", null ],
    [ "local_provisioning/app.c", "dc/d5b/local_provisioning_2app_8c-example.html", null ],
    [ "low_latency_app/app.c", "d9/d09/low_latency_app_2app_8c-example.html", null ],
    [ "minimal_app/app.c", "d7/db8/minimal_app_2app_8c-example.html", null ],
    [ "nfc/app.c", "d0/d36/nfc_2app_8c-example.html", null ],
    [ "positioning_app/app.c", "d2/d7a/positioning_app_2app_8c-example.html", null ],
    [ "provisioning_joining_node/app.c", "d5/da9/provisioning_joining_node_2app_8c-example.html", null ],
    [ "provisioning_proxy/app.c", "db/d30/provisioning_proxy_2app_8c-example.html", null ],
    [ "ruuvi_evk/app.c", "da/d90/ruuvi_evk_2app_8c-example.html", null ],
    [ "scheduler/app.c", "d6/da1/scheduler_2app_8c-example.html", null ],
    [ "shared_data/app.c", "d5/d87/shared_data_2app_8c-example.html", null ],
    [ "tinycbor/app.c", "dc/d2d/tinycbor_2app_8c-example.html", null ]
];